name: collabverse
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  form_builder_validators: ^11.2.0
  google_fonts: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
